routes/web.php
<?php

use App\Http\Controllers\Admin\BlogTrashController;
use App\Http\Controllers\Admin\UserBlogManagerController;
use App\Http\Controllers\BlogController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserManagerController;
use App\Http\Controllers\Admin\UserProfileController;
use App\Http\Controllers\Admin\AuthController as AdminAuth;
use App\Http\Controllers\Admin\BlogController as AdminBlog;
use App\Http\Controllers\Admin\IndexController as Admin;

Route::controller(AdminAuth::class)->group(function () {
	Route::middleware(['guest'])->group(function () {
		Route::get('/admin/auth', 'login')->name('admin.auth');
		Route::post('/admin/auth', 'authenticate');
	});

	Route::post('/admin/auth/logout', 'logout')->middleware(['auth'])->name('admin.auth.logout');
});

Route::group(['controller' => Admin::class, 'middleware' => ['auth']], function () {
	Route::redirect('/admin', '/admin/dashboard');
	Route::get('/admin/dashboard', 'index')->name('admin.dashboard');
});

Route::group(['controller' => UserManagerController::class, 'middleware' => 'auth'], function () {
	Route::get('/admin/user', 'index')->name('manager.user');
	Route::get('/admin/user/create', 'create')->name('manager.user.create');
	Route::post('/admin/user/create', 'store')->name('manager.user.store');
	Route::get('/admin/user/{user:username}', 'profile')->name('manager.user.profile');
	Route::get('/admin/user/{user:username}/edit', 'edit')->name('manager.user.edit');
	Route::patch('/admin/user/{user:username}/edit', 'update')->name('manager.user.update');
	Route::patch('/admin/user/{user:username}/edit/password', 'changePassword')->name('manager.user.update.password');
	Route::delete('/admin/user/{user}/delete', 'destroy')->name('manager.user.delete');
});

Route::group(['controller' => UserBlogManagerController::class, 'middleware' => 'auth'], function () {
	Route::get('/admin/user/{user:username}/blog', 'index')->name('manager.user.blog');
});

Route::group(['controller' => BlogTrashController::class, 'middleware' => 'auth'], function () {
	Route::get('/admin/blog/trash', 'viewAny')->name('admin.blog.trash');
	Route::patch('/admin/blog/trash/{blog:slug}/restore', 'restore')->name('admin.blog.trash.restore')->withTrashed();
	Route::patch('/admin/blog/trash/restore-all', 'restoreAll')->name('admin.blog.trash.restore-all')->withTrashed();
	Route::delete('/admin/blog/trash/{blog:slug}/force-delete', 'forceDelete')->name('admin.blog.trash.force-delete')->withTrashed();
	Route::delete('/admin/blog/trash/force-delete-all', 'forceDeleteAll')->name('admin.blog.trash.force-delete-all')->withTrashed();
	Route::get('/admin/blog/trash/{blog:slug}', 'view')->name('admin.blog.trash.view')->withTrashed();
});

Route::group(['controller' => AdminBlog::class, 'middleware' => ['auth']], function () {
	Route::get('/admin/blog', 'index')->name('admin.blog');
	Route::get('/admin/blog/create', 'create')->name('admin.blog.create');
	Route::post('/admin/blog/create', 'store')->name('admin.blog.store');
	Route::get('/admin/blog/{blog:slug}', 'view')->name('admin.blog.show')->withTrashed();
	Route::delete('/admin/blog/{blog:slug}', 'delete')->name('admin.blog.destroy')->withTrashed();
	Route::get('/admin/blog/{blog:slug}/edit', 'edit')->name('admin.blog.edit');
	Route::patch('/admin/blog/{blog:slug}/edit', 'update')->name('admin.blog.update');
	Route::patch('/admin/blog/{blog:slug}/upload', 'upload')->name('admin.blog.upload');
});

Route::group(['controller' => UserProfileController::class, 'middleware' => 'auth'], function () {
	Route::get('/admin/profile', 'index')->name('admin.profile');
	Route::get('/admin/profile/edit', 'edit')->name('admin.profile.edit');
	Route::patch('/admin/profile/edit', 'update')->name('admin.profile.update');
	Route::patch('/admin/profile/edit/password', 'changePassword')->name('admin.profile.update.password');
});

Route::group(['controller' => BlogController::class], function () {
	Route::get('/', 'index')->name('index');
	Route::get('/{blog:slug}', 'view')->name('blog.view');
});

app/Http/Controllers/Admin/UserManagerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ChangeUserPasswordRequest;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use App\Services\UserService;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;

class UserManagerController extends Controller
{
	private UserService $userService;

	/**
	 * @param UserService $userService
	 */
	public function __construct(UserService $userService)
	{
		$this->userService = $userService;
	}

	/**
	 * @param Request $request
	 * @return Application|Factory|View
	 * @throws AuthorizationException
	 */
	public function index(Request $request)
	{
		$this->authorize('view', $request->user());

		return view('page.admin.manager.index', [
			'users' => User::withCount('blogs')->orderBy('role')->get(),
		]);
	}

	/**
	 * @param Request $request
	 * @param User $user
	 * @return Application|Factory|View|RedirectResponse|Redirector
	 * @throws AuthorizationException
	 */
	public function profile(Request $request, User $user)
	{
		$this->authorize('view', $request->user());

		if (auth()->user()->is($user))
			return redirect(route('admin.profile'));

		return view('page.admin.profile.index', [
			'user' => $user,
		]);
	}

	/**
	 * @param Request $request
	 * @return Application|Factory|View
	 * @throws AuthorizationException
	 */
	public function create(Request $request)
	{
		$this->authorize('create', $request->user());

		return view('page.admin.manager.create');
	}

	/**
	 * @param CreateUserRequest $request
	 * @return RedirectResponse
	 * @throws AuthorizationException
	 */
	public function store(CreateUserRequest $request)
	{
		$this->authorize('create', $request->user());

		$data = $request->validated();

		return $this->userService->register($data) ?
			redirect()->intended(route('manager.user')) :
			back()->withErrors(['create-admin-failed' => __('Gagal membuat admin')]);
	}

	/**
	 * @param Request $request
	 * @param User $user
	 * @return Application|Factory|RedirectResponse|View
	 * @throws AuthorizationException
	 */
	public function edit(Request $request, User $user)
	{
		$this->authorize('update', $user);

		if (auth()->user()->is($user))
			return redirect()->route('admin.profile.edit');

		return view('page.admin.manager.edit', [
			'user' => $user,
		]);
	}

	/**
	 * @param UpdateUserRequest $request
	 * @param User $user
	 * @return Application|RedirectResponse|Redirector
	 * @throws AuthorizationException
	 */
	public function update(UpdateUserRequest $request, User $user)
	{
		$this->authorize('update', $user);

		$data = $request->validated();

		$user = $this->userService->updateProfile($user, $data);

		return $user ?
			redirect(route('manager.user.edit', ['user' => $user]))
				->with(['update-user-profile-success' => __('Update profil berhasil')])
			:
			back()
				->withErrors(['update-user-profile-failed' => __('Update profil gagal')]);
	}

	/**
	 * @param ChangeUserPasswordRequest $request
	 * @param User $user
	 * @return RedirectResponse
	 * @throws AuthorizationException
	 */
	public function changePassword(ChangeUserPasswordRequest $request, User $user)
	{
		$this->authorize('update', $user);

		['new-password' => $password] = $request->validated();

		return $this->userService->changePassword($user, $password) ?
			back()->with(['change-user-password-success' => __('Ganti password user berhasil')]) :
			back()->withErrors(['change-user-password-failed' => __('Ganti password user gagal')]);
	}

	/**
	 * @param Request $request
	 * @param User $user
	 * @return RedirectResponse
	 * @throws AuthorizationException
	 */
	public function destroy(Request $request, User $user)
	{
		$this->authorize('delete', $user);

		return $this->userService->delete($user) ?
			back()->with(['delete-user-success' => 'User berhasil dihapus']) :
			back()->withErrors(['delete-user-failed' => 'User gagal dihapus']);
	}
}

resources/views/page/admin/manager/create.blade.php
@extends('layouts.index')

@section('title', 'Admin')

@section('body')
    <x-partials.admin.navbar :title="__('Buat Admin')"/>

    @include('partials.admin.sidebar', ['active' => 'manager'])

    <x-partials.admin.main class="font-montserrat pt-24 min-h-screen">
        <form action="{{ route('manager.user.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="flex space-x-20">
                <div>
                    <div class="flex flex-col items-center space-y-4">
                        <img class="rounded-full border border-slate-600 w-40"
                             src="{{ asset("storage/avatar/default.png") }}">
                        <form action="{{ '' }}" method="post">
                            <button type="submit"
                                    class="font-medium text-slate-600 hover:text-blue-700 active:text-blue-800">{{ __('Unggah avatar') }}</button>
                        </form>
                    </div>
                </div>

                <div class="flex flex-col space-y-6 w-96">
                    <x-form.input
                            id="name"
                            name="name"
                            :label="__('Nama')"
                            :value="old('name')"
                    />

                    <x-form.input
                            id="username"
                            name="username"
                            :label="__('Username')"
                            :value="old('username')"
                    />

                    <x-form.input
                            id="email"
                            name="email"
                            type="email"
                            :label="__('Email')"
                            :value="old('email')"
                    />

                    <x-form.input
                            id="password"
                            name="password"
                            type="password"
                            :label="__('Password')"
                    />

                    <div class="flex flex-col space-y-2">
                        <span class="text-sm font-medium text-slate-600">{{ __('Role') }}</span>
                        <label>
                            <div class="inline-flex items-center space-x-1">
                                <input id="role" type="radio" name="role"
                                       value="{{ \App\Enums\UserRole::ADMIN->value }}">
                                <span class="text-sm font-medium text-slate-600">{{ Str::title(\App\Enums\UserRole::ADMIN->name) }}</span>
                            </div>
                        </label>
                        <label>
                            <div class="inline-flex items-center space-x-1">
                                <input id="role" type="radio" name="role"
                                       value="{{ \App\Enums\UserRole::NORMAL->value }}">
                                <span class="text-sm font-medium text-slate-600">{{ Str::title(\App\Enums\UserRole::NORMAL->name) }}</span>
                            </div>
                        </label>
                    </div>

                    <button type="submit"
                            class="text-sm font-medium rounded text-white bg-blue-600 hover:bg-blue-700 active:bg-blue-800 px-4 py-2">
                        <span>{{ __('Buat') }}</span>
                    </button>
                </div>
            </div>
        </form>
    </x-partials.admin.main>
@endsection

resources/views/page/admin/manager/edit.blade.php
@extends('layouts.index')

@section('title', "Edit - {$user->name}")

@section('body')
    <x-partials.admin.navbar :title="__('Edit profil')">
        <x-slot:actions>
            @can('delete', $user)
                <form action="{{ route('manager.user.delete', ['user' => $user]) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <x-button.button-link color="red">
                        <x-icon.trash class="w-4 h-4"/>
                        <span class="ml-2">{{ __('Hapus') }}</span>
                    </x-button.button-link>
                </form>
            @endcan
        </x-slot:actions>
    </x-partials.admin.navbar>

    @include('partials.admin.sidebar', ['active' => 'manager'])

    <x-partials.admin.main class="ml-96 font-montserrat pt-24 pb-72">
        <div class="grid grid-cols-2 gap-20">
            <section id="avatar-update" class="col-span-2">
                <div class="space-y-6">
                    <div class="flex space-x-12">
                        <img class="rounded-full border border-slate-600 w-40"
                             src="{{ asset("storage/avatar/{$user->avatar}") }}">
                        <div class="flex flex-col justify-center space-y-4">
                            <h1 class="font-medium text-4xl text-slate-900">{{ $user->name }}</h1>
                            <div class="flex space-x-2 divide-x divide-slate-400 text-slate-600">
                                <span>{{ $user->role() }}</span>
                                <span class="pl-2">{{ $user->email }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section id="profile-update">
                <form action="{{ route('manager.user.update', ['user' => $user]) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="space-y-6 pt-6">
                        <div class="font-light border-b border-slate-100 pb-6">{{ __('Informasi Pribadi') }}</div>
                        @if(session()->has('update-user-profile-success'))
                            <x-alert
                                    :name="session('update-user-profile-success')"
                                    type="success"
                            />
                        @endif

                        @error('update-user-profile-failed')
                        <x-alert
                                :name="$errors->first('update-user-profile-failed')"
                                type="error"
                        />
                        @enderror

                        <x-form.input
                                id="name"
                                name="name"
                                :label="__('Nama')"
                                :value="old('name', $user->name)"
                                :placeholder="$user->name"
                        />

                        <x-form.input
                                id="username"
                                name="username"
                                :label="__('Username')"
                                :value="old('username', $user->username)"
                                :placeholder="$user->username"
                        />

                        <x-form.input
                                id="email"
                                name="email"
                                type="email"
                                :label="__('Email')"
                                :value="old('email', $user->email)"
                                :placeholder="$user->email"
                        />

                        @can('attachRole', $user)
                            <div class="flex flex-col space-y-2">
                                <span class="text-sm font-medium text-slate-600">{{ __('Role') }}</span>
                                <label>
                                    <div class="inline-flex items-center space-x-1">
                                        <input id="role" type="radio" name="role"
                                               value="{{ \App\Enums\UserRole::ADMIN->value }}" {{ $user->isAdmin() ? 'checked' : '' }}>
                                        <span
                                                class="text-sm font-medium text-slate-600">{{ Str::title(\App\Enums\UserRole::ADMIN->name) }}</span>
                                    </div>
                                </label>
                                <label>
                                    <div class="inline-flex items-center space-x-1">
                                        <input id="role" type="radio" name="role"
                                               value="{{ \App\Enums\UserRole::NORMAL->value }}" {{ $user->isNormal() ? 'checked' : '' }}>
                                        <span
                                                class="text-sm font-medium text-slate-600">{{ Str::title(\App\Enums\UserRole::NORMAL->name) }}</span>
                                    </div>
                                </label>
                                @error('role')
                                <div class="text-sm font-medium text-red-600">{{ $errors->first('role') }}</div>
                                @enderror
                            </div>
                        @endcan

                        <x-button.primary type="submit">
                            <span>{{ __('Update profil') }}</span>
                        </x-button.primary>
                    </div>
                </form>
            </section>

            <section id="change-password">
                <form action="{{ route('manager.user.update.password', ['user' => $user]) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="space-y-6 pt-6">
                        <div class="font-light border-b border-slate-100 pb-6">{{ __('Password') }}</div>

                        @if(session()->has('change-user-password-success'))
                            <x-alert
                                    :name="session('change-user-password-success')"
                                    type="success"
                            />
                        @endif

                        @error('change-user-password-failed')
                        <x-alert
                                :name="$errors->first('change-user-password-failed')"
                                type="error"
                        />
                        @enderror

                        <x-form.input
                                id="new-password"
                                name="new-password"
                                type="password"
                                :label="__('Password baru')"
                        />

                        <x-form.input
                                id="admin-password"
                                name="admin-password"
                                type="password"
                                :label="__('Password anda')"
                        />

                        <x-button.primary type="submit">
                            <span>{{ __('Ganti password') }}</span>
                        </x-button.primary>
                    </div>
                </form>
            </section>
        </div>
    </x-partials.admin.main>
@endsection

resources/views/page/admin/manager/index.blade.php
@extends('layouts.index')

@section('title', 'Users')

@section('body')
    <x-partials.admin.navbar :title="__('Users')">
        <x-slot:actions>
            @can('create', \App\Models\User::class)
                <x-button.link href="{{ route('manager.user.create') }}">
                    <x-icon.plus class="w-4 h-4"/>
                    <span class="ml-2">{{ __('Register user') }}</span>
                </x-button.link>
            @endcan
        </x-slot:actions>
    </x-partials.admin.navbar>

    @include('partials.admin.sidebar', ['active' => 'manager'])

    <x-partials.admin.main class="font-montserrat pt-24 min-h-screen">

        <div class="mb-4 w-96">
            @if(session()->has('delete-user-success'))
                <x-alert
                        :name="session('delete-user-success')"
                        type="success"
                />
            @endif

            @error('delete-user-failed')
            <x-alert
                    :name="$errors->first('delete-user-failed')"
                    type="error"
            />
            @enderror
        </div>

        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="text-xs text-slate-700 bg-slate-50 text-left">
                <tr>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Nama') }}
                    </th>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Email') }}
                    </th>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Username') }}
                    </th>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Role') }}
                    </th>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Tanggal dibuat') }}
                    </th>
                    <th scope="col" class="py-3 px-6 text-right">
                        {{ __('Total blog') }}
                    </th>
                    <th scope="col" class="py-3 px-6">
                        {{ __('Aksi') }}
                    </th>
                </tr>
                </thead>
                <tbody>

                @foreach($users as $user)
                    <tr class="bg-white border-b border-slate-100">
                        <td class="py-4 px-4">
                            <div class="flex items-center">
                                <img class="w-8 h-8 rounded-full" src="{{ asset("storage/avatar/{$user->avatar}") }}"
                                     alt="{{ $user->username }} avatar">
                                <span class="ml-4">{{ $user->name }}</span>
                            </div>
                        </td>
                        <td class="py-4 px-6">
                            {{ $user->email }}
                        </td>
                        <td class="py-4 px-6">
                            {{ $user->username }}
                        </td>
                        <td class="py-4 px-6">
                            <x-badge.role :role="\App\Enums\UserRole::from($user->role)"/>
                        </td>
                        <td class="py-4 px-6">
                            {{ \Illuminate\Support\Carbon::make($user->created_at)->format('d F Y') }}
                        </td>
                        <td class="py-4 px-6 text-right">
                            <x-button.link href="{{ route('manager.user.blog', ['user' => $user]) }}">
                                {{ $user->blogs_count }}
                            </x-button.link>
                        </td>
                        <td class="py-4 px-6">
                            <div class="flex space-x-4">
                                @can('view', $user)
                                    <a href="{{ route('manager.user.profile', ['user' => $user]) }}"
                                       class="text-slate-600 hover:text-blue-700 active:text-blue-800 p-2">
                                        <x-icon.info class="w-4 h-4"/>
                                    </a>
                                @endcan

                                @can('update', $user)
                                    <a href="{{ route('manager.user.edit', ['user' => $user]) }}"
                                       class="text-slate-600 hover:text-blue-700 active:text-blue-800 p-2">
                                        <x-icon.edit class="w-4 h-4"/>
                                    </a>
                                @endcan

                                @can('delete', $user)
                                    <form action="{{ route('manager.user.delete', ['user' => $user]) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                                class="text-slate-600 hover:text-red-700 active:text-red-800 p-2">
                                            <x-icon.trash class="w-4 h-4"/>
                                        </button>
                                    </form>
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </x-partials.admin.main>
    <span class="text-red-600 text-yellow-600 text-green-600"></span>
@endsection